/*
 * namelist.h -- An ArrayList class that grows as data are added
 * 
 * Author: Samuel J. Berman (sberma04)
 * 
 * CS 11: Lab 9
 * Tufts University, Fall 2021
 * 
 * Note: Do not edit this file
 * 
 */

#ifndef NAMELIST_H
#define NAMELIST_H

#include <iostream>
using namespace std;

class NameList {
public:
        NameList();                      // Constructor: defaults to 
                                         //       INIT_SIZE elements
        ~NameList();                     // Destructor

        int    getSize();                // Return the number of names that
                                         // are currently in the list
        int    getCapacity();            // Returns current capacity
        string getValAt(int index);      // Returns element at the given index
        void   add(string val);          // Adds element to end of array
        bool   insertAt(string val, int index); // Set value at given index
                                                // Index must be less
                                                // than current size of the 
                                                // NameList object
        void   print();                 // Prints current NameList
        void   revPrint();              // Prints current NameList in reverse
        bool   readFromFile(string);    // Reads from named file
        
private:
        static const int INIT_SIZE = 10;

        int     capacity;     // Current capacity of the NameList
        int     n_elements;   // Number of elements stored the list
        string *data;         // Pointer to array of data

        void   expand();      // Doubles the capacity of the array
};

#endif
